ApiKey = "${CIVITAI_API_KEY}"

SavePath = "/workspace/civitai-export"

DatabasePath = "civitai.db"

Sort = "Most Downloaded"
Period = "AllTime"
Limit = 100
Types = [
    "Checkpoint",
    "TextualInversion",
    "Hypernetwork",
    "AestheticGradient",
    "LORA",
    "LoCon",
    "DoRA",
    "Controlnet",
    "Upscaler",
    "MotionModule",
    "VAE",
    "Poses",
    "Wildcards",
    "Workflows",
    "Detection",
    "Other"
]
BaseModels = [
    'Other'
]
GetNsfw = true

GetOnlyPrimaryModel = false
GetPruned = false
GetFp16 = false
IgnoreBaseModels = [] # ["1.5", "0.9", "2.0", "2.1", "1.4", "other"]
IgnoreFileNameStrings = [] # ["alpha", "beta", "inpainting", "preview"]

LogApiRequests = true
SaveMetadata = true
ApiDelayMs = 2000
ApiClientTimeoutSec = 60
DefaultConcurrency = 2
